######################################################################
# Automatically generated by qmake (3.0) Tue May 24 06:33:03 2016
######################################################################

TEMPLATE = app
TARGET = ldd_out_copier
INCLUDEPATH += . 

QT-=gui
QT+=core
CONFIG+= c++14 console release
# Input
SOURCES += main.cc
